- hosts: yandex_kub_test
  tasks:    
  - name: Add helm repo bitnami
    kubernetes.core.helm_repository:
      name: bitnami
      repo_url: https://charts.bitnami.com/bitnami
  - name: Add helm repo httpserver
    git:
      repo: https://github.com/ustmish/httpserver-helm.git
      dest: /tmp/helm_repo_httpserver    
  - name: Install Postgresql
    kubernetes.core.helm:
      name: postgres-test12349
      namespace: test123
      chart_ref: bitnami/postgresql
  - name: Install httpserver
    kubernetes.core.helm:
      name: httpserver-test
      namespace: test123
      chart_ref: /tmp/helm_repo_httpserver/httpserver


      

